name: meditation
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.1.5
  just_audio: ^0.9.36

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/img/icon.png" # <-- your icon file (512x512 PNG recommended)

  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/img/
   - assets/song/mediataion.mp3
 
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: HelveticaNeue
        fonts:
        - asset: assets/font/HelveticaNeueLight.otf
        - asset: assets/font/HelveticaNeueMedium.otf
          weight: 600
        - asset: assets/font/HelveticaNeueBold.otf
          weight: 700
        - asset: assets/font/HelveticaNeueThin.otf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
